### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Muskelmagier** [leszekhanusz/diffusion-ui#42]
Won't work for me 
I am a Windows user

Message inside the web-user.bat

Traceback (most recent call last):
  File "C:\Users\Heimann David\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 273, in run_predict    output = await app.blocks.process_api(
  File "C:\Users\Heimann David\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 739, in process_api    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\Heimann David\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 638, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\Heimann David\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 2118, in preprocess
    return process_single_file(x)
  File "C:\Users\Heimann David\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 2088, in process_single_file
    f["name"],
TypeError: 'bool' object is not subscriptable

have tried using git fetch origin pull/1276/head and git checkout FETCH_HEAD
 Used the Automatic1111 sorted option and localhost is http://localhost:7860/

And i used the most recent version

**Comment by leszekhanusz** [comment]
Thanks for your detailled issue.

Could you please try this:
* open the left panel in diffusionui.com
* Be sure to have "Automatic1111 sorted" selected in the dropdown
* click on the ⓘ icon to go to the model info tab
* click on the "Reset to default values" button
* click Yes to confirm

**Comment by leszekhanusz** [comment]
If that does not solve your problem, please copy-paste the beginning of the text in the webui.bat console.
It should look something like:

```
venv "E:\Development\git-repos\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)
Commit hash: 938c83c388208b9cc48acb2842dc453c33c82a95
Installing requirements for Web UI
Launching Web UI with arguments:    
```

**Comment by Muskelmagier** [comment]
I think know my problem.

It is recommended by in the instalation guide of the Automatic repo to use the "webui-user.bat" to start up the programm. 
But your webui wants me to use the "webui.bat".

Now that i used the "webui.bat" it works and i now longer get error 500. its probably the same with other people.

**Comment by leszekhanusz** [comment]
Thanks again for your feedback. I've added an explanation on how to make it work [in the docs](https://diffusionui.readthedocs.io/en/latest/backends/automatic1111.html)
